# Trading Bot Configuration

# Exchange Configuration
exchange:
  name: "kraken"
  api_rate_limit: 15  # calls per second
  fee: 0.0026  # 0.26% trading fee

# Trading Pairs
assets:
  symbols:
    - "BTC/USDT"
    - "ETH/USDT"
    - "BNB/USDT"
    - "ADA/USDT"
    - "SOL/USDT"
    - "XRP/USDT"
    - "DOT/USDT"
    - "DOGE/USDT"
    - "AVAX/USDT"
    - "MATIC/USDT"
    - "LINK/USDT"
    - "LTC/USDT"
    - "ATOM/USDT"
    - "UNI/USDT"
    - "ALGO/USDT"

# Timeframes - UPDATED to include 30m
timeframes:
  - "5m"
  - "15m"
  - "30m"   # NEW
  - "1h"
  - "4h"
  - "1d"
  - "1w"

# Data Configuration
data:
  base_path: "./data"
  raw_data_path: "./data/raw"
  processed_data_path: "./data/processed"
  features_path: "./data/features"
  database:
    type: "sqlite"  # or "postgresql"
    sqlite_path: "./data/trading_bot.db"
    # postgresql:
    #   host: "localhost"
    #   port: 5432
    #   database: "trading_bot"
    #   user: "trader"

# Feature Engineering
features:
  price_based:
    return_periods: [1, 5, 10, 20, 50, 100]
    ratio_periods: [5, 10, 20]
  
  technical_indicators:
    rsi:
      periods: [14, 21]
    macd:
      fast: 12
      slow: 26
      signal: 9
    bollinger:
      period: 20
      std: 2
    atr:
      period: 14
    adx:
      period: 14
    
  volume:
    obv: true
    volume_ratio_period: 20
    
  pattern_recognition:
    enabled: true
    min_pattern_strength: 0.7
    
  multi_timeframe:
    enabled: true
    lookback_periods: [5, 10, 20]
    
  feature_selection:
    method: "mutual_info"  # or "rfe", "importance"
    n_features: 50
    
# Machine Learning Configuration
ml:
  model_type: "xgboost"  # or "lightgbm"
  
  xgboost:
    n_estimators: 1000
    max_depth: 7
    learning_rate: 0.01
    subsample: 0.8
    colsample_bytree: 0.8
    
  lightgbm:
    n_estimators: 1000
    max_depth: 7
    learning_rate: 0.01
    feature_fraction: 0.8
    bagging_fraction: 0.8
    
  labeling:
    method: "triple_barrier"
    profit_taking_multiplier: 2.0
    stop_loss_multiplier: 1.0
    max_holding_period: 100
    
  validation:
    method: "walk_forward"
    train_period_days: 180
    test_period_days: 30
    step_days: 30
    
# Reinforcement Learning Configuration
rl:
  algorithm: "dqn"
  
  environment:
    initial_balance: 10000
    leverage: 1
    
  agent:
    state_dim: 63
    action_dim: 3  # Hold, Buy, Sell
    hidden_dim: 256
    learning_rate: 0.001
    
  training:
    episodes: 1000
    batch_size: 32
    memory_size: 10000
    epsilon_start: 1.0
    epsilon_end: 0.01
    epsilon_decay: 0.995
    gamma: 0.99
    target_update_freq: 10
    
# Risk Management
risk:
  max_position_size: 0.1  # 10% of portfolio
  max_positions: 3
  stop_loss: 0.02  # 2%
  take_profit: 0.04  # 4%
  max_drawdown: 0.15  # 15%
  daily_loss_limit: 0.05  # 5%
  
  position_sizing:
    method: "kelly"  # or "fixed", "volatility"
    kelly_fraction: 0.25
    
  circuit_breakers:
    enabled: true
    consecutive_losses: 5
    pause_duration_hours: 24
    
# Backtesting Configuration
backtesting:
  initial_capital: 10000
  commission: 0.0026
  slippage: 0.001
  
  metrics:
    - "total_return"
    - "sharpe_ratio"
    - "max_drawdown"
    - "win_rate"
    - "profit_factor"
    - "calmar_ratio"
    
# Paper Trading Configuration
paper_trading:
  enabled: false
  initial_balance: 10000
  update_frequency: "1m"
  duration_days: 30
  
# Live Trading Configuration
live_trading:
  enabled: false
  initial_balance: 1000
  max_order_size: 100
  update_frequency: "1m"
  
  safety:
    dry_run: true
    confirm_orders: true
    emergency_stop: true
    
# Monitoring & Logging
monitoring:
  log_level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  log_file: "./logs/trading.log"
  error_file: "./logs/errors.log"
  performance_file: "./logs/performance.log"
  
  dashboard:
    enabled: true
    host: "127.0.0.1"
    port: 8050
    update_interval: 60  # seconds
    
  alerts:
    enabled: false
    email:
      smtp_server: "smtp.gmail.com"
      smtp_port: 587
      sender: "bot@example.com"
    
  metrics_export:
    prometheus:
      enabled: false
      port: 9090
      
# Performance Targets
targets:
  sharpe_ratio: 1.5
  max_drawdown: 0.15
  win_rate: 0.45
  annual_return: 0.20
  
# System Settings
system:
  random_seed: 42
  n_jobs: -1  # Use all CPU cores
  cache_enabled: true
  debug_mode: false